#! /bin/sh
LIBEVL_VERSION=59
LIBEVL_VERSION_STUFFIX=-2
LIBEVL_PACKAGE_VERSION=${LIBEVL_VERSION}${LIBEVL_VERSION_STUFFIX}

KERNEL_RT=true
if $KERNEL_RT ; then
	KERNEL_CONFIG=kconfig-base-config-6.12.94+deb13-rt-amd64.txt
	KERNEL_LOCAL_VERSION=-xenomai4-r${LIBEVL_VERSION}-rt
else
	KERNEL_CONFIG=kconfig-base-config-6.12.94+deb13-amd64.txt
	KERNEL_LOCAL_VERSION=-xenomai4-r${LIBEVL_VERSION}
fi
KERNEL_VERSION=6.12.90
KERNEL_VERSION_CIP=-cip24
KERNEL_VERSION_STUFFIX=3
KERNEL_PACKAGE_VERSION=${KERNEL_VERSION}${KERNEL_VERSION_CIP}${KERNEL_LOCAL_VERSION}_${KERNEL_VERSION}-${KERNEL_VERSION_STUFFIX}
